Lesson2
KateRin1103/KateRin_JavaIntensive pull request #2
Opened 2021-02-20 15:15 UTC by KateRin1103

This is my second homework

2021-02-20 19:46 UTC, zhdanok requested changes
See notes

2021-02-20 19:46 UTC, zhdanok commented on src/main/java/jrr/by/lesson2/ArrayService.java
> +    }
Правильно по сути, но не по заданию. По заданию нужно было вернуть 0 или -1 (не помню) если массив пустой (new int [0])

2021-02-20 19:46 UTC, zhdanok commented on src/main/java/jrr/by/lesson2/ArrayService.java
> +        return (double) summing / array.length;
Если массив пустой (длина 0), то выдаст ошибку при делении на ноль

2021-02-20 19:46 UTC, zhdanok commented on src/main/java/jrr/by/lesson2/Palindrome.java
> +    }
Не выполнено условие : не учитывать знаки препинания и пробелы.

2021-02-20 19:46 UTC, zhdanok commented on src/test/java/jrr/by/lesson1/MathOperationsTest.java
> +        assertEquals(12, result);
Тест же завалится. Нужно использовать assertNotEquels. Даже тест на ошибку должен отрабатывать без ошибок)

2021-02-20 19:46 UTC, zhdanok commented on src/test/java/jrr/by/lesson1/MathOperationsTest.java
> +
См. Выше. + Добавить исключение при делении на 0

2021-02-20 19:46 UTC, zhdanok commented on src/test/java/jrr/by/lesson2/ArrayServiceTest.java
> +    }
Тест ничего не проверяет. Сравни длину вернувшегося массива с заданным числом

2021-02-20 19:46 UTC, zhdanok commented on src/test/java/jrr/by/lesson2/ArrayServiceTest.java
> +    }
Тест ничего не проверяет. Вызови метод два раза. Сравни полученные массивы. Убедись, что они не равны. ==> Метод работает правильно

2021-02-20 19:46 UTC, zhdanok commented on src/test/java/jrr/by/lesson2/ArrayServiceTest.java
> +        logger.info("Sorted array " + Arrays.toString(array));
Нужно развернуть не отсортированный массив. У тебя в expected отсортированный

2021-02-20 20:26 UTC, integratorBY approved these changes
lgfm

2021-02-20 20:26 UTC, integratorBY commented on src/main/java/jrr/by/lesson2/ArrayService.java
> +    }
Не по условию да, но молодец!

2021-02-20 20:26 UTC, integratorBY commented on src/main/java/jrr/by/lesson2/ArrayService.java
> +        return (double) summing / array.length;
да, согласен

2021-02-20 20:26 UTC, integratorBY commented on src/test/java/jrr/by/lesson2/ArrayServiceTest.java
> +    }
да, Люда молодец!

2021-02-20 20:26 UTC, integratorBY commented on src/test/java/jrr/by/lesson2/ArrayServiceTest.java
> +    }
согласен!

2021-02-21 13:02 UTC, drozdi-k approved these changes

2021-02-21 13:02 UTC, drozdi-k approved these changes

2021-02-21 13:03 UTC, merged